"""
Generate HTML summary report from backtest results.
Called by GitHub Actions after backtest.
"""
import json
import argparse
from pathlib import Path
from datetime import datetime
from loguru import logger
from utils.logger import setup_logger


HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Backtest Report - {pair}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
        .container {{ max-width: 900px; margin: auto; background: white; padding: 30px; border-radius: 8px; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #34495e; }}
        .metrics-grid {{ display: grid; grid-template-columns: repeat(3, 1fr); gap: 15px; margin: 20px 0; }}
        .metric-card {{
            background: #ecf0f1; padding: 15px; border-radius: 6px;
            text-align: center; border-left: 4px solid #3498db;
        }}
        .metric-value {{ font-size: 1.8em; font-weight: bold; color: #2c3e50; }}
        .metric-label {{ font-size: 0.85em; color: #7f8c8d; margin-top: 5px; }}
        .positive {{ color: #27ae60; }}
        .negative {{ color: #e74c3c; }}
        .neutral {{ color: #2980b9; }}
        img {{ width: 100%; border-radius: 6px; margin: 20px 0; }}
        .footer {{ text-align: center; color: #95a5a6; font-size: 0.85em; margin-top: 30px; }}
        table {{ width: 100%; border-collapse: collapse; }}
        th, td {{ padding: 10px; border: 1px solid #ddd; text-align: left; }}
        th {{ background: #3498db; color: white; }}
        tr:nth-child(even) {{ background: #f9f9f9; }}
    </style>
</head>
<body>
<div class="container">
    <h1>📊 Backtest Report — {pair}</h1>
    <p><strong>Generated:</strong> {timestamp}</p>

    <h2>Performance Overview</h2>
    <div class="metrics-grid">
        <div class="metric-card">
            <div class="metric-value {return_class}">{total_return:+.2f}%</div>
            <div class="metric-label">Total Return</div>
        </div>
        <div class="metric-card">
            <div class="metric-value neutral">{sharpe:.3f}</div>
            <div class="metric-label">Sharpe Ratio</div>
        </div>
        <div class="metric-card">
            <div class="metric-value negative">-{max_dd:.2f}%</div>
            <div class="metric-label">Max Drawdown</div>
        </div>
        <div class="metric-card">
            <div class="metric-value neutral">{win_rate:.1f}%</div>
            <div class="metric-label">Win Rate</div>
        </div>
        <div class="metric-card">
            <div class="metric-value neutral">{profit_factor:.2f}</div>
            <div class="metric-label">Profit Factor</div>
        </div>
        <div class="metric-card">
            <div class="metric-value neutral">{total_trades}</div>
            <div class="metric-label">Total Trades</div>
        </div>
    </div>

    <h2>Equity Curve & Analysis</h2>
    <img src="backtest_test_report.png" alt="Backtest Report Chart"/>

    <h2>Full Metrics</h2>
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        {metrics_rows}
    </table>

    <div class="footer">
        Generated by Forex RL Bot | GitHub Actions Run
    </div>
</div>
</body>
</html>
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pair", default="EURUSD")
    parser.add_argument("--split", default="test")
    args = parser.parse_args()

    setup_logger()

    metrics_path = Path(f"results/{args.pair}/backtest_{args.split}_metrics.json")

    if not metrics_path.exists():
        logger.error(f"Metrics file not found: {metrics_path}")
        return

    with open(metrics_path) as f:
        metrics = json.load(f)

    # Build metrics table rows
    metrics_rows = "\n".join(
        f"<tr><td>{k.replace('_', ' ').title()}</td><td>{v:.4f}" 
        f"{'%' if 'pct' in k else ''}</td></tr>"
        for k, v in metrics.items()
        if isinstance(v, (int, float))
    )

    html = HTML_TEMPLATE.format(
        pair=args.pair,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        total_return=metrics["total_return_pct"],
        return_class="positive" if metrics["total_return_pct"] > 0 else "negative",
        sharpe=metrics["sharpe_ratio"],
        max_dd=metrics["max_drawdown_pct"],
        win_rate=metrics["win_rate_pct"],
        profit_factor=metrics["profit_factor"],
        total_trades=metrics["total_trades"],
        metrics_rows=metrics_rows,
    )

    report_path = Path(f"results/{args.pair}/backtest_report.html")
    with open(report_path, "w") as f:
        f.write(html)

    logger.info(f"HTML Report saved → {report_path}")


if __name__ == "__main__":
    main()
